### ISSUE TITLE
File Missing

### ISSUE THREAD

**Issue by Wpj-001** [BayesianSCA/k-trace-CCA#1]
Hello, I am very interested in the code you submitted, but when I ran the code, I found that the file "ntt_bp" is missing. Could you please provide it?
![image](https://github.com/BayesianSCA/k-trace-CCA/assets/164879804/d29c1688-67ed-4dec-938e-6ece1fc5c7ba)

**Comment by sil-van** [comment]
Won't fix. Please read your debug output carefully: your python interpreter is not the required version.
