### ISSUE TITLE
Faced some error when running 

### ISSUE THREAD

**Issue by trevor-yap** [BayesianSCA/k-trace-CCA#2]
Hi, I faced a similar issue. I followed the set up in README.md and received the following error. 
It would be much appreciated how to fix this part. Thanks~ 

![image](https://github.com/BayesianSCA/k-trace-CCA/assets/35169648/f92a1f4d-906d-40d8-9156-dd4eaa95a5f2)

**Comment by trevor-yap** [comment]
see https://github.com/BayesianSCA/k-trace-CCA/issues/3

**Comment by sil-van** [comment]
Fixed with e839a03
