### ISSUE TITLE
Another error 

### ISSUE THREAD

**Issue by trevor-yap** [BayesianSCA/k-trace-CCA#3]
![image](https://github.com/BayesianSCA/k-trace-CCA/assets/35169648/de574fe1-322d-4f13-877d-15f1307c5dea)

There is another error here.

Update:
But I have actually, change the prior Option for the function `add_threaded_var_node`  in `graph.rs` file, as describe in another issue (see here: https://github.com/BayesianSCA/k-trace-CCA/issues/2) to:
![image](https://github.com/BayesianSCA/k-trace-CCA/assets/35169648/c9a9e04b-1d6d-46ff-bdb4-15315d184f3e)

I fixed this by changing the order `rust_node_args=[prior, *vrange, self_start]`  to `rust_node_args=[*vrange, self_start, prior]`

![image](https://github.com/BayesianSCA/k-trace-CCA/assets/35169648/9d82f20d-a6c7-4e7c-ada8-6ff435f2704b)

**Comment by sil-van** [comment]
Fixed with e839a03
